name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  call-shared-deploy:
    uses: bogdanovmn/github-actions/.github/workflows/deploy-js.yml@master
    with:
      service_name: "orbit"
    secrets:
      SSH_CONFIG_JSON: ${{ secrets.SSH_CONFIG_JSON }}